{
    "type": "bundle",
    "id": "bundle--b3117e44-cbfc-4aa6-a8f4-dcd8d7410cfc",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ef81ada3-c7f9-49a2-ab34-c362631a6b6a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-07-28T00:05:04.334639Z",
            "modified": "2023-07-28T00:05:04.334639Z",
            "name": "CVE-2023-38603",
            "description": "The issue was addressed with improved checks. This issue is fixed in iOS 16.6 and iPadOS 16.6, macOS Ventura 13.5. A remote user may be able to cause a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-38603"
                }
            ]
        }
    ]
}