{
    "type": "bundle",
    "id": "bundle--14928325-936c-4e36-af83-f27dadd912ff",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--24e003aa-20fa-40a4-84c3-8a1f0bb40fbf",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-12-09T00:16:41.881663Z",
            "modified": "2023-12-09T00:16:41.881663Z",
            "name": "CVE-2023-6507",
            "description": "An issue was found in CPython 3.12.0 `subprocess` module on POSIX platforms. The issue was fixed in CPython 3.12.1 and does not affect other stable releases.\n\nWhen using the `extra_groups=` parameter with an empty list as a value (ie `extra_groups=[]`) the logic regressed to not call `setgroups(0, NULL)` before calling `exec()`, thus not dropping the original processes' groups before starting the new process. There is no issue when the parameter isn't used or when any value is used besides an empty list.\n\nThis issue only impacts CPython processes run with sufficient privilege to make the `setgroups` system call (typically `root`).\n\n",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-6507"
                }
            ]
        }
    ]
}