{
    "type": "bundle",
    "id": "bundle--746d45b8-4893-4fcc-b583-b768e8095794",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5a260e98-f47d-4b07-9035-8f75ddc2fd11",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-23T00:04:53.704574Z",
            "modified": "2023-08-23T00:04:53.704574Z",
            "name": "CVE-2022-48565",
            "description": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-48565"
                }
            ]
        }
    ]
}