{
    "type": "bundle",
    "id": "bundle--bdfc8e68-9ea4-4df6-8fc5-d0f1ee17ee01",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--43a47d3f-c0cf-4517-b080-a14f87dbf8be",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-16T00:05:18.24533Z",
            "modified": "2023-08-16T00:05:18.24533Z",
            "name": "CVE-2023-39661",
            "description": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-39661"
                }
            ]
        }
    ]
}