{
    "type": "bundle",
    "id": "bundle--66c1f8cc-070d-4750-b295-ef9709935f9b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--600e5a77-41d8-473a-91b6-ca3ea9d881e1",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-06-14T00:05:05.237203Z",
            "modified": "2023-06-14T00:05:05.237203Z",
            "name": "CVE-2023-3159",
            "description": "A use after free issue was discovered in driver/firewire in outbound_phy_packet_callback in the Linux Kernel. In this flaw a local attacker with special privilege may cause a use after free problem when queue_event() fails.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-3159"
                }
            ]
        }
    ]
}